apiVersion: v1
kind: Pod
metadata:
  name: miconfigmappod
  namespace: paradigma
spec:
  containers:
  - name: ubuntu
    image: ubuntu:20.04
    command: ['sh', '-c', "echo $(MIVARIABLE) && sleep 3600"]
    env:
    - name: MIVARIABLE
      valueFrom:
        configMapKeyRef:
          name: miconfigmap
          key: miClave