apiVersion: v1
kind: Pod
metadata:
  name: mimulticontainerpod
  namespace: paradigma
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: ubuntu
    image: ubuntu:20.04
    command: ['sh', '-c', 'while true; do sleep 30; done;']