apiVersion: v1
kind: Pod
metadata:
  name: mireadinesspod
  namespace: paradigma
spec:
  containers:
    - name: nginx
      image: nginx
      readinessProbe:
        exec:
          command:
          - cat
          - /tmp/readi
        initialDelaySeconds: 5
        periodSeconds: 5