apiVersion: v1
kind: Service
metadata:
  name: postgre
  namespace: example
spec:
  type: ClusterIP
  selector:
    app: postgresapp
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    
  