apiVersion: v1
kind: Service
metadata:
  name: servicenodeport
  namespace: example
spec:
  type: NodePort
  selector:
    app: postgresapp
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432