apiVersion: batch/v1
kind: Job
metadata:
  name: miinsertausuarios
  namespace: example
spec:
  template:
    spec:      
      containers:
      - name: mijavaappinsertausuarios
        image: fernandocabadas/postgresqlapp:latest
        args:
        - /bin/sh
        - -c
        - java -cp PostgresqlApp.jar insertausuarios
      restartPolicy: Never
  backoffLimit: 4
