apiVersion: batch/v1
kind: Job
metadata:
  name: mijob
  namespace: paradigma
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        args:
        - /bin/sh
        - -c
        - date; echo Ejecutando un job
      restartPolicy: Never
  backoffLimit: 4