apiVersion: v1
kind: Pod
metadata:
  name: milivenesspod
  namespace: paradigma
spec:
  containers:
    - name: nginx
      image: nginx
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/live
        initialDelaySeconds: 5
        periodSeconds: 5