apiVersion: v1
kind: Service
metadata:
  name: miservicenodeport
  namespace: paradigma
spec:
  type: NodePort
  selector:
    app: miappclusternodeport
  ports:
  - nodePort: 30100
    port: 8080
    targetPort: 80
    protocol: TCP
  